language: objective-c

xcode_project: Swiftility.xcodeproj
xcode_scheme: Swiftility
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

#before_install:  # to fix xctool issue since Xcode 7.3
#  brew uninstall xctool && brew install --HEAD xctool

before_install:
  - gem install xcpretty

script:
  - set -o pipefail
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination 'name=iPhone 6' test | xcpretty -c
